### ISSUE TITLE
REST API refactoring

### ISSUE THREAD

**Issue by klangner** [carldata/hydra-http#120]
Here is a proposition for the top level resources:

  * channels (Get data for given channel)
  * calculations (load, save, delete, execute)
  * face (convert)
  * testcases (add, remove, update, execute)
  * real_time_job (GET)

**Comment by sharpcoding** [comment]
"api" / "execute"
"api" / "convert"
"api" / "gettimeseries"
"api" / "calculations" / "get"
"api" / "calculations" / "save"
"api" / "calculations" / "delete"
"api" / "healthcheck"
"rtj" / "check"
"rtj" / "verify-exists"
"rtj" / "tests" / "get"
"rtj" / "tests" / "delete"
"rtj" / "tests" / "save"
