### ISSUE TITLE
NoSuchElementException: main 

### ISSUE THREAD

**Issue by wenta** [carldata/hydra-http#158]
```
type:error

Runtime exception: java.util.NoSuchElementException: main
```

**Comment by tpichlak** [comment]
![image](https://user-images.githubusercontent.com/16462422/33648033-3ec9685a-da58-11e7-8a82-8fb9d0dace64.png)

**Comment by klangner** [comment]
The problem here is that function main expects single channel, when in the input channels we have 2.

IMHO we need better error message here. Like 
"wrong number of channels"
