### ISSUE TITLE
Refactor api for hydra_items

### ISSUE THREAD

**Issue by klangner** [carldata/hydra-http#166]
With "hydra_items"

It means that we need to replace function calls. For example:
 * "getRealTimeJobTests" should be replaced with "items"

**Comment by tpichlak** [comment]
![restapihydraitems](https://user-images.githubusercontent.com/16462422/33758252-d0e9d854-dbfd-11e7-91d7-ffc1bb7124ba.jpg)

**Comment by tpichlak** [comment]
Change id in hydra_items from uuid to text.
