### ISSUE TITLE
Fix the problem with error message from the backend

### ISSUE THREAD

**Issue by klangner** [carldata/hydra-http#65]
Currently all problems are reported as invalid date

**Comment by wenta** [comment]
It looks that BE send _correct_ (error) message. Frontend do not consume it. _Invalid Date_ shows up at DateTime column, and _NaN_ in Computed Value column, which is fine.  
For example if we execute:
`def main(xs: TimeSeries): TimeSeries = xs+1`
api will send:
`Wrong return type for function main
 Expected: ValueType(TimeSeries)
Got: Left(Type error for operation: +)`
I think that on FE we can introduce optionally label with error message.

**Comment by klangner** [comment]
Yes. That's good idea.

**Comment by tpichlak** [comment]
Possible version of JSON:
{
    "errorCode" : "error code",
    "timeSeries" : "Timeseries tak jak poprzednio" 
}

**Comment by klangner** [comment]
Or maybe something like this:
Return data:
```
{
"type": "data",
"data":{"index":["2015-01-01", "2015-01-02"], "values":[1.2, 3.4]}
}
```
Return error message
```
{
"type": "error",
"error":"Can't compile script"
}
```

Every response always contains type field. And then rest of the fields depends on this type.

**Comment by tpichlak** [comment]
What do you think about this kind of schema:

**Comment by tpichlak** [comment]
The actual schema:
'''
type:data

2017-04-02T02:32:03, 4.0
2017-04-02T03:32:04, 4.0
2017-04-02T04:32:03, 4.0
2017-04-02T05:32:03, 4.0
2017-04-02T06:32:03, 4.0
2017-04-02T07:32:04, 4.0
2017-04-02T08:32:03, 4.0
2017-04-02T09:32:03, 4.0
2017-04-02T10:32:03, 4.0
2017-04-02T11:32:03, 4.0
2017-04-02T12:32:03, 4.0
'''

Or for error:

'''
type:error

mismatched input '=' expecting ':'
'''

**Comment by wenta** [comment]
Fixed.
