### ISSUE TITLE
backend returns empty data set for non existing channel or empty/wrong date 

### ISSUE THREAD

**Issue by tpichlak** [carldata/hydra-http#74]
Is it a bug or a feature? maybe it should return an error instead of empty data set.

**Comment by klangner** [comment]
I would say that if the channel doesn't exists, then error message would be helpful. But if for a given data range there is no data, then the current behavior is ok. Even if the data range is wrong

**Comment by wenta** [comment]
If table does not contains any data for channel does not mean that channel not exist. I think we should close this.
